#! /bin/sh
bash /home/prashant/.config/bspwm/specific.sh&
nitrogen --restore&
picom --config /home/prashant/.compton.conf&
xrdb ~/.Xresources&
dunst&
greenclip daemon&
eval "$(ssh-agent -s)"&

bspc config normal_border_color "#928374"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#928374"
bspc config active_border_color "#928374"
bspc config split_ratio          0.52
bspc config click_to_focus 	button1
bspc config pointer_follows_focus	true
bspc config borderless_monocle	false
bspc config gapless_monocle	true
bspc config swallow_first_click	true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor	true

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a "*:stick" state=floating sticky=on center
bspc rule -a "*:stick1" state=floating sticky=on
bspc rule -a "*:stick2" state=floating sticky=on
bspc rule -a "*:float" state=floating
bspc rule -a "*:cal" state=floating sticky=on
bspc rule -a Steam:"Friends List" state=floating
bspc rule -a "dotnet" state=floating
bspc rule -a polybar layer=above
bspc rule -a "Nm-connection-editor" state=floating

redshift -l -35.3:149&
xsetroot -cursor_name left_ptr&
