#! /bin/sh
xrandr --output HDMI-A-0 --right-of DVI-D-1 --mode 2560x1440 --pos 2560x0 --rotate normal --output DVI-D-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal
nitrogen --restore&
picom --config /home/prashant/.compton.conf&
xrdb ~/.Xresources&
polybar bar1&
polybar bar2&
dunst&

bspc monitor DVI-D-1 -d one two three four five
bspc monitor HDMI-A-0 -d six seven eight nine ten
bspc config top_padding        0
bspc config bottom_padding     70
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width         4
bspc config window_gap          20

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color2"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color2"

bspc config split_ratio          0.52
bspc config click_to_focus 	button1
#bspc config swallow_first_click	true
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true
bspc config pointer_follows_monitor	true
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a "*:stick" state=floating sticky=on center
bspc rule -a "*:stick1" state=floating sticky=on
bspc rule -a "*:stick2" state=floating sticky=on
bspc rule -a "*:float" state=floating
bspc rule -a "*:cal" state=floating sticky=on
bspc rule -a Steam:"Friends List" state=floating
#bspc rule -a polybar layer=above
bspc rule -a "dotnet" state=floating

redshift -l -35.3:149&
xsetroot -cursor_name left_ptr&
export PATH=/home/prashant/.local/bin:$PATH
