#! /bin/sh
xrandr --output DP-0 --right-of HDMI-0 --mode 2560x1440 --rate 144 --pos 2560x0 --rotate normal --output HDMI-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal
nitrogen --restore&
picom --config /home/prashant/.compton.conf&
xrdb ~/.Xresources&
polybar bar1&
polybar bar2&
dunst&

bspc monitor HDMI-0 -d one two three four five
bspc monitor DP-0 -d six seven eight nine ten
bspc config top_padding        10
bspc config bottom_padding     80
bspc config left_padding       10
bspc config right_padding      10
bspc config border_width         4
bspc config window_gap          30
bspc config normal_border_color "#928374"
bspc config active_border_color "#928374"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#928374"
bspc config split_ratio          0.52
bspc config click_to_focus 	button1
#bspc config swallow_first_click	true
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true
bspc config pointer_follows_monitor	true
bspc config borderless_monocle	false
bspc config gapless_monocle	true

bspc rule -a mpv state=floating
bspc rule -a "*:sxiv" state=floating
bspc rule -a "*:stick" state=floating sticky=on center
bspc rule -a "*:stick1" state=floating sticky=on
bspc rule -a "*:stick2" state=floating sticky=on
bspc rule -a "*:float" state=floating
bspc rule -a "*:cal" state=floating sticky=on
bspc rule -a Steam:"Friends List" state=floating
#bspc rule -a polybar layer=above
bspc rule -a "dotnet" state=floating

redshift -l -35.3:149&
xsetroot -cursor_name left_ptr&
export PATH=/home/prashant/.local/bin:$PATH
